import Head from "next/head";
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Pastport</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="apple-mobile-web-app-title" content="Pastport" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <div className="relative flex h-full w-full items-center justify-center">
        {children}
      </div>
    </>
  );
};

export default Layout;
